# Generated by Django 5.2.5 on 2025-12-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='total_volume',
            field=models.FloatField(default=0.0, help_text='Volumen total acumulado en litros'),
        ),
    ]
