# Generated by Django 5.2.5 on 2025-12-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensorreading_total_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_valve_state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], default='unknown', help_text='Estado actual de la válvula (reportado por ESP32)', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='desired_valve_state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('none', 'None')], default='none', help_text='Estado deseado de la válvula (comando pendiente para ESP32)', max_length=10),
        ),
    ]
